version: "3.6"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'webpages'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'ThinkPad'
      MYSQL_ROOT_PASSWORD: 'root'
    security_opt:
      - seccomp:unconfined
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - /docker/mysqlData/:/volume/mysql/
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "0.0.0.0:3001:80"
    environment:
      PMA_HOST: mysql
